Repository GoogleCloudPlatform/gke-binary-auth-demo, pull requests merged in 2019-11, with the labels that each got.

#21 Rename `--public-key-file` to `--pgp-public-key-file`
  README-QWIKLABS.md
Labels: approved, cla: yes, gke-helmsman, lgtm, size/XS

#22 Rename `--pgp-key-fingerprint` argument to `--public-key-id`
  README-QWIKLABS.md
Labels: approved, cla: yes, gke-helmsman, lgtm, size/XS

#20 Removes 'beta' designation for 2 GA products.
  README.md
Labels: cla: yes, gke-helmsman, lgtm, size/S

#23 Jenkinsfile
  Jenkinsfile
Labels: approved, cla: yes, gke-helmsman, lgtm, size/M
